function createfigure(YMatrix1, Y1, Y2)
%CREATEFIGURE(YMATRIX1,Y1,Y2)
%  YMATRIX1:  matrix of y data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 17-Jul-2009 08:29:20

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1,'FontWeight','bold','FontSize',8,...
    'FontName','Verdana');
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1,'Marker','+','LineStyle','none');
set(plot1(8),'MarkerSize',8,'Marker','*');

% Create title
title('Amplitude da tensão','FontWeight','bold','FontSize',11,...
    'FontName','Verdana');

% Create xlabel
xlabel('Nº da barra','FontWeight','bold','FontSize',9,'FontName','Verdana');

% Create ylabel
ylabel('e(%)','FontWeight','bold','FontSize',9,'FontName','Verdana');

% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1,'FontWeight','bold','FontSize',8,...
    'FontName','Verdana');
box('on');
hold('all');

% Create plot
plot(Y1,'Parent',subplot2,'MarkerSize',8,'Marker','*','LineStyle','none');

% Create title
title('Ângulo de fase da tensão','FontWeight','bold','FontSize',11,...
    'FontName','Verdana');

% Create xlabel
xlabel('Nº da barra','FontWeight','bold','FontSize',9,'FontName','Verdana');

% Create ylabel
ylabel('e (min)','FontWeight','bold','FontSize',9,'FontName','Verdana');

% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1,'FontWeight','bold','FontSize',8,...
    'FontName','Verdana');
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([0 3]);
box('on');
hold('all');

% Create plot
plot(Y2,'Parent',subplot3,'MarkerSize',8,'Marker','*','LineStyle','none');

% Create title
title('Resíduos normalizados (pu)','FontWeight','bold','FontSize',11,...
    'FontName','Verdana');

% Create xlabel
xlabel('Telemedida (nº)','FontWeight','bold','FontSize',9,...
    'FontName','Verdana');

% Create ylabel
ylabel('Rn (pu)','FontWeight','bold','FontSize',9,'FontName','Verdana');

